"""
This type stub file was generated by pyright.
"""

from pebble.decorators import sighandler, synchronized
from pebble.common import ProcessExpired, ProcessFuture
from pebble.functions import waitforqueues, waitforthreads
from pebble.pool import MapFuture, ProcessMapFuture, ProcessPool, ThreadPool

__author__ = ...
__version__ = ...
__license__ = ...
__all__ = ['waitforthreads', 'waitforqueues', 'synchronized', 'sighandler', 'ProcessFuture', 'MapFuture', 'ProcessMapFuture', 'ProcessExpired', 'ProcessPool', 'ThreadPool']
