"""
This type stub file was generated by pyright.
"""

from pebble.pool.thread import ThreadPool
from pebble.pool.process import ProcessPool
from pebble.pool.base_pool import MapFuture, ProcessMapFuture

__all__ = ['ThreadPool', 'ProcessPool', 'MapFuture', 'ProcessMapFuture']
